In [168]:
%run ../processing/functions.ipynb

In [1]:
%run pre_processing_template.ipynb

The quantity of objects is:  21317
The shapes of the objects are:
ids:  (21317,)
labels:  (21317,)
images:  (21317, 4, 30, 46)
train_images:  (18000, 4, 30, 46)
Other useful object: "test_images"
1.13.1


In [204]:
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D, Conv3D, MaxPooling3D, ZeroPadding3D

In [171]:
class_names = ['Ia','Ib','Ibc','Ic','II','IIL','IIP','IIn']

In [79]:
#train_images.shape
#test_images

In [146]:
test_swaped = np.swapaxes(test_images,1,3)
train_swaped = np.swapaxes(train_images,1,3)

In [144]:
test_images.shape

(3317, 4, 30, 46)

In [148]:
test_swaped.shape

(3317, 46, 30, 4)

# Model Convolution NN 2D

In [150]:
img_rows, img_cols = 30, 46
input_shape = (img_cols, img_rows, 4)

model_cv = Sequential()

model_cv.add(Conv2D(64, kernel_size=(4,4), padding='same', activation='relu', input_shape=input_shape))
model_cv.add(Conv2D(64, kernel_size=(3,3), padding='same', activation='relu', input_shape=input_shape))
model_cv.add(MaxPooling2D(pool_size=(2,2)))
model_cv.add(Conv2D(64, kernel_size=(3,3), padding='same', activation='relu', input_shape=input_shape))
model_cv.add(MaxPooling2D(pool_size=(2,2)))


model_cv.add(Flatten())
model_cv.add(Dense(8, activation=tf.nn.softmax))

model_cv.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_17 (Conv2D)           (None, 46, 30, 64)        4160      
_________________________________________________________________
conv2d_18 (Conv2D)           (None, 46, 30, 64)        36928     
_________________________________________________________________
max_pooling2d_12 (MaxPooling (None, 23, 15, 64)        0         
_________________________________________________________________
conv2d_19 (Conv2D)           (None, 23, 15, 64)        36928     
_________________________________________________________________
max_pooling2d_13 (MaxPooling (None, 11, 7, 64)         0         
_________________________________________________________________
flatten_20 (Flatten)         (None, 4928)              0         
_________________________________________________________________
dense_50 (Dense)             (None, 8)                 39432     
Total para

In [151]:
model_cv.compile(optimizer='adam', #optimizer = 'adadelta'
              loss='sparse_categorical_crossentropy', #loss = "binary_crossentropy"
              metrics=['accuracy'])

In [153]:
model_cv.fit(train_swaped, train_labels, #validation_split = 0.1
             epochs=10) 

Epoch 1/10
18000/18000 [==============================] - 141s 8ms/sample - loss: 1.1743 - acc: 0.6222
Epoch 2/10
18000/18000 [==============================] - 141s 8ms/sample - loss: 0.9224 - acc: 0.7160
Epoch 3/10
18000/18000 [==============================] - 145s 8ms/sample - loss: 0.8783 - acc: 0.7248
Epoch 4/10
18000/18000 [==============================] - 143s 8ms/sample - loss: 0.8313 - acc: 0.7352
Epoch 5/10
18000/18000 [==============================] - 142s 8ms/sample - loss: 0.7952 - acc: 0.7421
Epoch 6/10
18000/18000 [==============================] - 141s 8ms/sample - loss: 0.7566 - acc: 0.7525
Epoch 7/10
18000/18000 [==============================] - 142s 8ms/sample - loss: 0.7241 - acc: 0.7634
Epoch 8/10
18000/18000 [==============================] - 143s 8ms/sample - loss: 0.6931 - acc: 0.7720
Epoch 9/10
18000/18000 [==============================] - 142s 8ms/sample - loss: 0.6648 - acc: 0.7789
Epoch 10/10
18000/18000 [==============================] - 141s 8ms/sampl

# Train using simple Layers: tf.keras.layers.Dense

In [122]:
img_rows, img_cols = 30, 46
input_shape = (4, img_rows, img_cols)

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(4, 30, 46)), #aqui mudar o novo shape () 64x40 iu 46x30, x4 talvez 
    #Transform the 2d array into a 1d with mxn 
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(8, activation=tf.nn.softmax) #exit layer, change to the number of class we have ()
])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_18 (Flatten)         (None, 5520)              0         
_________________________________________________________________
dense_43 (Dense)             (None, 128)               706688    
_________________________________________________________________
dense_44 (Dense)             (None, 128)               16512     
_________________________________________________________________
dense_45 (Dense)             (None, 128)               16512     
_________________________________________________________________
dense_46 (Dense)             (None, 128)               16512     
_________________________________________________________________
dense_47 (Dense)             (None, 128)               16512     
_________________________________________________________________
dense_48 (Dense)             (None, 8)                 1032      
Total para

In [126]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [132]:
model.fit(train_images, train_labels, epochs=10)

Epoch 1/10
18000/18000 [==============================] - 22s 1ms/sample - loss: 1.3186 - acc: 0.5605
Epoch 2/10
18000/18000 [==============================] - 19s 1ms/sample - loss: 1.2928 - acc: 0.5668
Epoch 3/10
18000/18000 [==============================] - 22s 1ms/sample - loss: 1.2581 - acc: 0.5698
Epoch 4/10
18000/18000 [==============================] - 18s 1ms/sample - loss: 1.1575 - acc: 0.6217
Epoch 5/10
18000/18000 [==============================] - 27s 2ms/sample - loss: 1.0776 - acc: 0.6574
Epoch 6/10
18000/18000 [==============================] - 20s 1ms/sample - loss: 1.0496 - acc: 0.6695
Epoch 7/10
18000/18000 [==============================] - 26s 1ms/sample - loss: 1.0329 - acc: 0.6772
Epoch 8/10
18000/18000 [==============================] - 19s 1ms/sample - loss: 1.0242 - acc: 0.6787
Epoch 9/10
18000/18000 [==============================] - 16s 888us/sample - loss: 0.9992 - acc: 0.6879
Epoch 10/10
18000/18000 [==============================] - 20s 1ms/sample - loss

# CNN1 another structure

In [118]:
img_rows, img_cols = 30, 46
input_shape = (4, img_rows, img_cols)

cnn1 = Sequential()
cnn1.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=input_shape))
cnn1.add(MaxPooling2D(pool_size=(2, 2)))
cnn1.add(Dropout(0.2))

cnn1.add(Flatten())

cnn1.add(Dense(128, activation='relu'))
cnn1.add(Dense(10, activation='softmax'))

cnn1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_13 (Conv2D)           (None, 2, 28, 32)         13280     
_________________________________________________________________
max_pooling2d_9 (MaxPooling2 (None, 1, 14, 32)         0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 1, 14, 32)         0         
_________________________________________________________________
flatten_17 (Flatten)         (None, 448)               0         
_________________________________________________________________
dense_41 (Dense)             (None, 128)               57472     
_________________________________________________________________
dense_42 (Dense)             (None, 10)                1290      
Total params: 72,042
Trainable params: 72,042
Non-trainable params: 0
_________________________________________________________________


In [125]:
cnn1.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [131]:
cnn1.fit(train_images, train_labels, epochs=10)

Epoch 1/10
18000/18000 [==============================] - 10s 581us/sample - loss: 1.1340 - acc: 0.6315
Epoch 2/10
18000/18000 [==============================] - 10s 561us/sample - loss: 1.1208 - acc: 0.6397
Epoch 3/10
18000/18000 [==============================] - 19s 1ms/sample - loss: 1.1229 - acc: 0.6356
Epoch 4/10
18000/18000 [==============================] - 24s 1ms/sample - loss: 1.1212 - acc: 0.6397
Epoch 5/10
18000/18000 [==============================] - 25s 1ms/sample - loss: 1.1176 - acc: 0.6378
Epoch 6/10
18000/18000 [==============================] - 25s 1ms/sample - loss: 1.1143 - acc: 0.6422
Epoch 7/10
18000/18000 [==============================] - 25s 1ms/sample - loss: 1.1054 - acc: 0.6448
Epoch 8/10
18000/18000 [==============================] - 22s 1ms/sample - loss: 1.1048 - acc: 0.6471
Epoch 9/10
18000/18000 [==============================] - 17s 921us/sample - loss: 1.0983 - acc: 0.6490
Epoch 10/10
18000/18000 [==============================] - 13s 747us/sample 

# Evaluation

In [156]:
test_loss_model, test_acc_model = model.evaluate(test_images, test_labels)
test_loss_cv, test_acc_cv = model_cv.evaluate(test_swaped, test_labels)
test_loss_cnn, test_acc_cnn = cnn1.evaluate(test_images, test_labels)

print('Test accuracy model:', test_acc_model)
print('Test accuracy model_cv:', test_acc_cv)
print('Test accuracy cnn:', test_acc_cnn)

3317/3317 [==============================] - 1s 298us/sample - loss: 1.1046 - acc: 0.6548
Test accuracy model: 0.65511006
Test accuracy model_cv: 0.73198676
Test accuracy cnn: 0.6548086


In [158]:
predictions = model_cv.predict(test_swaped)
print(predictions[0], '\n',
      'Predicted: ', np.argmax(predictions[0]), ' True one: ', test_labels[0])

[9.5722053e-06 8.8233675e-04 2.1723541e-04 2.3779287e-03 9.8737490e-01
 2.6400987e-05 3.5215167e-03 5.5901473e-03] 
 Predicted:  4  True one:  4


In [162]:
from sklearn.metrics import confusion_matrix
y_true = test_labels
y_pred = []
for i in predictions:
    y_pred.append(np.argmax(i))

cm = confusion_matrix(y_true, y_pred)

In [167]:
cm_plot_labels = [1,2,3,4,5,6,7,8]
plot_confusion_matrix(y_true, y_pred, cm_plot_labels, title = "Confusion cv")

TypeError: only integer scalar arrays can be converted to a scalar index

In [175]:
confusion_matrix

<function sklearn.metrics.classification.confusion_matrix(y_true, y_pred, labels=None, sample_weight=None)>

In [172]:
conversion

{'IIL': 5,
 'IIP': 7,
 'II_': 4,
 'IIn': 6,
 'Ia_': 0,
 'Ib_': 1,
 'Ibc': 2,
 'Ic_': 3}

In [177]:
class_names

['Ia', 'Ib', 'Ibc', 'Ic', 'II', 'IIL', 'IIP', 'IIn']

In [206]:
def plot_confusion_matrix(y_true, y_pred, classes,
                          normalize=False,
                          title=None,
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if not title:
        if normalize:
            title = 'Normalized confusion matrix'
        else:
            title = 'Confusion matrix, without normalization'

    # Compute confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    # Only use the labels that appear in the data
    #classes = classes[unique_labels(y_true, y_pred)]
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    fig, ax = plt.subplots()
    im = ax.imshow(cm, interpolation='nearest', cmap=cmap)
    ax.figure.colorbar(im, ax=ax)
    # We want to show all ticks...
    ax.set(xticks=np.arange(cm.shape[1]),
           yticks=np.arange(cm.shape[0]),
           # ... and label them with the respective list entries
           xticklabels=classes, yticklabels=classes,
           title=title,
           ylabel='True label',
           xlabel='Predicted label')

    # Rotate the tick labels and set their alignment.
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right",
             rotation_mode="anchor")

    # Loop over data dimensions and create text annotations.
    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(j, i, format(cm[i, j], fmt),
                    ha="center", va="center",
                    color="white" if cm[i, j] > thresh else "black")
    fig.tight_layout()
    return ax


In [208]:
np.set_printoptions(precision=2)

# Plot non-normalized confusion matrix
plot_confusion_matrix(y_true, y_pred, classes=class_names,
                      title='Confusion matrix, without normalization')

# Plot normalized confusion matrix
plot_confusion_matrix(y_true, y_pred, classes=class_names, normalize=True,
                      title='Normalized confusion matrix')

plt.show()

Confusion matrix, without normalization
[[ 575   56    4   25  140    3    3    0]
 [ 113   38    1   14   66    1    0    0]
 [  14    4    2    5   18    0    1    0]
 [  47   10    0   20   88    1    3    0]
 [  39    9    1   23 1737    2   14    0]
 [  31    9    0    4   19   12    1    0]
 [   3    1    0    2   81    0   43    0]
 [   4    1    0    2   26    0    0    1]]
Normalized confusion matrix
[[7.13e-01 6.95e-02 4.96e-03 3.10e-02 1.74e-01 3.72e-03 3.72e-03 0.00e+00]
 [4.85e-01 1.63e-01 4.29e-03 6.01e-02 2.83e-01 4.29e-03 0.00e+00 0.00e+00]
 [3.18e-01 9.09e-02 4.55e-02 1.14e-01 4.09e-01 0.00e+00 2.27e-02 0.00e+00]
 [2.78e-01 5.92e-02 0.00e+00 1.18e-01 5.21e-01 5.92e-03 1.78e-02 0.00e+00]
 [2.14e-02 4.93e-03 5.48e-04 1.26e-02 9.52e-01 1.10e-03 7.67e-03 0.00e+00]
 [4.08e-01 1.18e-01 0.00e+00 5.26e-02 2.50e-01 1.58e-01 1.32e-02 0.00e+00]
 [2.31e-02 7.69e-03 0.00e+00 1.54e-02 6.23e-01 0.00e+00 3.31e-01 0.00e+00]
 [1.18e-01 2.94e-02 0.00e+00 5.88e-02 7.65e-01 0.00e+00 0.00e+

In [203]:
import matplotlib
matplotlib.matplotlib_fname()


'/home/felipematheus/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/matplotlibrc'

In [202]:
import matplotlib.rcsetup as rcsetup
print(rcsetup.all_backends)

['GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']


In [ ]:
GTK3Agg